version: '3'
services:
  frontend:
    build:
      context: ./frontend  # Path to the frontend directory containing the Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend  # Path to the backend directory containing the Dockerfile
      dockerfile: src/main/docker/Dockerfile.jvm  # Path to the Dockerfile
    ports:
      - "8080:8080"
